/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hnbpofuyqvdcrqlkpkil"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuYnBvZnV5cXZkY3JxbGtwa2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDU3ODIsImV4cCI6MjA3MDQ4MTc4Mn0.56NVeU_jhiADWV0jPxOWAtt_awr--gCLut5kKwcG44M"